---
- name: Nessus for EzyAdmin
  hosts: all
  tasks:
    - name: 'Define EzyAdmin API URL for register connector'
      set_fact:
        ezyadmin_register_connector_url: 'https://api.netway.ezyadmin.com/external/server/connector/nessus/hostname/{{ inventory_hostname }}/register/true'

    - name: 'Main | Register connector to EzyAdmin - Nessus'
      uri:
        url: '{{ ezyadmin_register_connector_url }}'
        method: PUT
        status_code: [200, 201]
      when:
        - ezyadmin_register_connector_url is defined
        - ansible_os_family != "Windows"
